sudo: required
dist: bionic
language: csharp
mono: none
dotnet: 3.1.101
solution: Etdb.UserService.AspNetCore.sln
env:
  global:
    - DocumentDbContextOptions__ConnectionString="mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017"
    - DocumentDbContextOptions__DatabaseName="Etdb_UserService_Dev_Testing"
    - RedisCacheOptions__Configuration="${RedisConnection}"
    - RedisCacheOptions__InstanceName="Etdb_UserService_Travis"
    - ASPNETCORE__ENVIRONMENT="CI"
stages:
  - build
  - test
  - create_client
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet build -c Release
    - stage: test
      name: run-tests
      services:
        - mongodb
        - redis-server
      before_script:
        - sh install_link_libgdiplus.sh
        - sh setup-mongodb-user.sh "$MONGODB_USERNAME" "$MONGODB_PASSWORD"
        - sh scaffold-db.sh
      script: ./run-tests.sh
    - stage: create-client
      name: create-client
      if: tag IS present
      before_script:
        - curl -sL https://deb.nodesource.com/setup_10.x | sudo -E bash -
        - sudo apt-get install -y nodejs
      script:
        - sh create-client.sh

