dist: bionic
language: csharp
solution: Etdb.UserService.AspNetCore.sln
mono: none
dotnet: 2.2.202
env:
  global:
    - DocumentDbContextOptions__ConnectionString="mongodb://${MONGODB_USERNAME}:${MONGODB_PASSWORD}@localhost:27017"
    - DocumentDbContextOptions__DatabaseName="Etdb_UserService_Dev_Testing"
    - RedisConfiguration__Connection="${RedisConnection}"
stages:
  - build
  - test
jobs:
  include:
    - stage: build
      name: build solution
      script: dotnet restore && dotnet build
    - stage: test
      name: run-tests
      services: 
        - mongodb
        - redis-server
      before_script:
        - sh setup-mongodb-user.sh "$MONGODB_USERNAME" "$MONGODB_PASSWORD"
        - sh scaffold-database.sh
      script: ./run-tests.sh

